name       : perl-data-dump
version    : 1.23
release    : 6
source     :
    - http://search.cpan.org/CPAN/authors/id/G/GA/GAAS/Data-Dump-1.23.tar.gz : af53b05ef1387b4cab4427e6789179283e4f0da8cf036e8db516ddb344512b65
license    : GPL-2.0
component  : programming.perl
summary    : Pretty printing of data structures
description: |
    Pretty printing of data structures
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
