name       : perl-data-dump
version    : '1.25'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/G/GA/GARU/Data-Dump-1.25.tar.gz : a4aa6e0ddbf39d5ad49bddfe0f89d9da864e3bc00f627125d1bc580472f53fbd
homepage   : https://metacpan.org/dist/Data-Dump
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Pretty printing of data structures
description: |
    Pretty printing of data structures
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
